name: kSabotage
main: kookaburra.minecraft.sabotage.kSabotage
version: @VERSION@
website: http://www.minecraftpvp.com
author: mcpvp.com
depend: [kNoHax, kShared, kCommon]
commands:                
  start:
    description:
    usage:           
  quit:
    description:
    usage:                   
  spawn:
    description:
    usage:           
  cpinv:
    description:
    usage:                           
  help:
    description:
    usage:
  herpderp:
    description:
    usage:          
  mobspawn:
    description:
    usage:
  vote:
    description:
    usage:
  shop:
    description:
    usage:
  saboteur:
    description:
    usage:
  stream:
    description:
    usage:
