name: kElite
main: kookaburra.minecraft.pvp.kElite
version: @VERSION@
website: http://www.minecraftpvp.com
author: mcpvp.com
depend: [kNoHax, kShared]
commands:
  team:
    description:
    usage: 
  t:
    description:
    usage:    
  track:
    description:
    usage:    
  addoldbank:
    description:
    usage:   
  fixspawn:
    description:
    usage:         
  drawspawn:
    description:
    usage:                    
  god:
    description:
    usage:           
  home:
    description:
    usage:           
  sneak:
    description:
    usage:           
  sethome:
    description:
    usage:           
  pos:
    description:
    usage:           
  cpinv:
    description:
    usage:           
  mod:
    description:
    usage:           
  unmod:
    description:
    usage:                                             
  spawn:
    description:
    usage:           
  go:
    description:
    usage:                
  warp:
    description:
    usage:                
  help:
    description:
    usage:
  herpderp:
    description:
    usage:
  fight:
    description:
    usage:                                  
  name:
    description:
    usage:         
  unmodall:
    description:
    usage:         
  lightning:
    description:
    usage:
  mobspawn:
    description:
    usage:
  storm:
    description:
    usage:
  goas:
    description:
    usage:
  regenspawn:
    description:
    usage:
  economy:
    description:
    usage:
  kit:
    description:
    usage:
  jail:
    description:
    usage:
  kitteam:
    description:
    usage:
  we:
    description:
    usage:
  enchant:
    description:
    usage:
  record:
    description:
    usage:
  countdown:
    description:
    usage:
  world:
    description:
    usage:
  spawnfight:
    description:
    usage:
  buy:
    description:
    usage:
  sell:
    description:
    usage:
  price:
    description:
    usage:
  deposit:
    description:
    usage:
  withdraw:
    description:
    usage:
  balance:
    description:
    usage: